### ISSUE TITLE
copyright clarification

### ISSUE THREAD

**Issue by anarcat** [jacobmarshall/go-locale#3]
could you provide a copyright statement for this source code? under which license is it distributed?

thanks

**Comment by jmshal** [comment]
Hi @anarcat,

Thanks for the issue. You're right, this repo should have included a license originally.

This has been fixed in https://github.com/jmshal/go-locale/commit/eb00fb25cc61bca7a5331ae576ae4a3d5572a1e4

The repo is licensed under MIT.
